AdmittanceControl:
    M_vx: 0.5
    M_vy: 0.5
    M_vz: 0.5
    D_vx: 1.0
    D_vy: 1.0
    D_vz: 1.0
    K_vx: 0.0
    K_vy: 0.0
    K_vz: 0.0
    segDurations: [3.0, 1.0, 6.0]
    polyCoeffs:
        - [ [0.0, 0.0, 0.0],
            [1.0, 0.5, -0.2],
            [0.1, 0.05, 0.02],
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 0.0] ]
        - [ [0.0, 0.0, 0.0],
            [1.0, 0.5, -0.2],
            [0.1, 0.05, 0.02],
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 0.0]]   # 第二段8×3系数矩阵
        - [ [0.0, 0.0, 0.0],
            [1.0, 0.5, -0.2],
            [0.1, 0.05, 0.02],
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 0.0] ]  # 第三段8×3系数矩阵
